

#
# Spring DataSource Support
#

spring.datasource:
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/postgres
  username: postgres
  password: pwd
  hikari:
    maximum-pool-size: 50
    minimum-idle: 5
    connection-timeout: 600000
    idle-timeout: 3000000
    validation-timeout: 300000
    leak-detection-threshold: 600000
spring.sql.init.mode: always

#
# Liquibase Support
#

spring.liquibase:
  change-log: classpath:changelog/changelog-master.yaml
  enabled: true
  database-change-log-lock-table: liquibase_changelog_lock
  database-change-log-table: liquibase_changelog
  default-schema: public

#
# Spring JPA Support
#

spring.data.jpa.repositories.enabled:  true

spring.jpa:
  generate-ddl: false
  open-in-view: true
  show-sql: true
  hibernate:
    ddl-auto: none
    naming:
      implicit-strategy:  org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      physical-strategy:  org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
  properties.hibernate:
    format_sql: false
    jdbc.batch_size: 100
    dialect.storage_engine: innodb
    query.plan_cache_max_size: 16
    query.plan_parameter_metadata_max_size: 128
    hibernate.jdbc.time_zone: UTC

#
# Spring Cache Support
#

spring.data.redis:
  host: localhost
  port: 6379

